"use strict";
const fallback={profile:{name:"YU",verified:true,role:"Roblox Script Creator | Developer",quote:"Better Scripts, Better Experience.",bio:"Hi! I’m YU, a Roblox script creator and developer.\nI make simple, useful and high quality scripts for everyone.\nThanks for visiting my page! 🙏",location:"Cambodia",joined:"Sep 2025",platform:"Roblox",image:"assets/reference-ui.png"},socials:[],stats:[],scripts:[],sections:{about:{enabled:true,title:"About Me"},projects:{enabled:true,title:"Projects"},scripts:{enabled:true,title:"Featured Scripts"},support:{enabled:true,title:"Support Me"},contact:{enabled:true,title:"Quick Links"}},ui:{title:"YU🔵 — Roblox Scripts & Tools",accent:"#14a8ff",theme:"dark",footer:"♛ YU🔵 | Roblox Scripts & Tools | Made with ❤️ for the community"},quickLinks:[]};
let config=fallback,toastTimer;
const $=s=>document.querySelector(s);
function showToast(message){const el=$("#toast");if(!el)return;el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2400)}
function scrollToSection(id){$("#"+id)?.scrollIntoView({behavior:"smooth"})}window.scrollToSection=scrollToSection;
function demoLink(name){showToast(`${name} link is ready — add your real URL in site-config.json`);return false}window.demoLink=demoLink;
function follow(){document.querySelectorAll("[data-follow]").forEach(b=>{b.classList.toggle("following",!b.classList.contains("following"));b.textContent=b.classList.contains("following")?"✓ Following":"♟ Follow"});showToast("Thanks for following YU 🔵")}
function render(c){document.title=c.ui?.title||fallback.ui.title;document.documentElement.style.setProperty("--blue",c.ui?.accent||fallback.ui.accent);$("#profileName").textContent=(c.profile.name||"YU")+(c.profile.verified?"🔵":"");$("#role").textContent=c.profile.role;$("#quote").textContent=`“${c.profile.quote||fallback.profile.quote}”`;$("#bio").innerHTML=(c.profile.bio||"").replace(/\n/g,"<br>");$("#profileImage").src=c.profile.image||fallback.profile.image;$("#meta").innerHTML=[c.profile.location,c.profile.joined&&`Joined ${c.profile.joined}`,c.profile.platform].filter(Boolean).map(x=>`<span>${x}</span>`).join("");$("#socials").innerHTML=(c.socials||[]).filter(x=>x.enabled!==false).map(x=>`<a href="${x.url||"#"}" ${x.url&&x.url!=="#"?'target="_blank" rel="noopener"':`onclick="return demoLink('${x.title||"Link"}')"`}>${x.icon||"◉"} <span>${x.title}</span><b>→</b></a>`).join("");$("#stats").innerHTML=(c.stats||[]).map(x=>`<div class="stat"><strong>${x.icon||"★"}</strong><b>${x.value||""}</b><small>${x.label||""}</small></div>`).join("");$("#scriptList").innerHTML=(c.scripts||[]).filter(x=>x.enabled!==false).map((x,i)=>`<article class="script"><div class="thumb" style="background-image:url('${x.thumbnail||""}');background-size:cover">${x.thumbnail?"":(x.name||"Script")}</div><div class="script-info"><h3>${x.name||"Untitled Script"}</h3><p>${x.description||""}</p><div class="tags">${(x.tags||[]).map(t=>`<span>${t}</span>`).join("")}</div></div><button class="get" data-url="${x.url||""}" data-name="${x.name||"Script"}">Get Script ↗</button></article>`).join("");$("#footer").textContent=c.ui?.footer||fallback.ui.footer;["about","projects","scripts","support","contact"].forEach(id=>{const s=c.sections?.[id];const el=$("#"+id);if(el){el.hidden=s?.enabled===false;const title=el.querySelector("h2");if(title&&s?.title)title.textContent=s.title}});if(c.ui?.theme==="light")document.body.classList.add("light")}
async function load(){try{const r=await fetch("data/site-config.json",{cache:"no-store"});if(!r.ok)throw Error();config=await r.json()}catch(e){showToast("Using starter configuration")}render(config)}
document.addEventListener("click",e=>{const f=e.target.closest("[data-follow]");if(f){follow();return}const s=e.target.closest("[data-scroll]");if(s){scrollToSection(s.dataset.scroll);return}const b=e.target.closest("[data-url]");if(b){const url=b.dataset.url;if(!url){showToast("Add a script URL in site-config.json");return}try{const u=new URL(url,location.href);if(u.hostname==="example.com"||u.hostname.endsWith(".example.com")){showToast("Replace the example.com script URL");return}if(!/^https?:$/.test(u.protocol)){showToast("Use a valid HTTP or HTTPS URL");return}window.open(u.href,"_blank","noopener,noreferrer")}catch{showToast("Add a valid script URL")}}});$("#theme")?.addEventListener("click",()=>{document.body.classList.toggle("light");showToast(document.body.classList.contains("light")?"Light mode enabled":"Dark mode enabled")});const io=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))})},{rootMargin:"-30% 0px -60%"});document.querySelectorAll("main section[id]").forEach(s=>io.observe(s));load();
