"use strict";
/* Authentication is intentionally server-side. Do not add passwords or secrets here. The API should use the existing Express session/auth middleware. */
const state={};const $=s=>document.querySelector(s);const statusEl=$("#status");
function status(message,error=false){statusEl.textContent=message;statusEl.style.color=error?"#ff8ca8":"#6ee7b7"}
function get(obj,path){return path.split(".").reduce((o,k)=>o?.[k],obj)}function set(obj,path,value){const keys=path.split(".");let o=obj;keys.slice(0,-1).forEach(k=>{if(!o[k]||typeof o[k]!=="object")o[k]={};o=o[k]});o[keys.at(-1)]=value}
async function request(url,options={}){const r=await fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(r.status===401||r.status===403)throw Error("Admin authentication required");if(!r.ok)throw Error(`Request failed (${r.status})`);return r.json()}
function bindPaths(){document.querySelectorAll("[data-path]").forEach(el=>{const value=get(state,el.dataset.path);if(el.type==="checkbox")el.checked=Boolean(value);else el.value=value??"";el.oninput=()=>set(state,el.dataset.path,el.type==="checkbox"?el.checked:el.value)})}
function editor(key,fields){const root=$(key==="socials"?"#socialEditor":key==="scripts"?"#scriptEditor":"#statEditor");root.innerHTML="";(state[key]||[]).forEach((item,i)=>{const box=document.createElement("div");box.className="item";fields.forEach(f=>{const label=document.createElement("label");label.textContent=f.label;const input=document.createElement(f.type==="textarea"?"textarea":"input");input.type=f.type==="checkbox"?"checkbox":f.type||"text";if(input.type==="checkbox")input.checked=item[f.key]!==false;else input.value=Array.isArray(item[f.key])?item[f.key].join(", "):item[f.key]||"";input.oninput=()=>item[f.key]=input.type==="checkbox"?input.checked:f.key==="tags"?input.value.split(",").map(x=>x.trim()).filter(Boolean):input.value;label.append(input);box.append(label)});const del=document.createElement("button");del.textContent="Delete";del.className="danger";del.onclick=()=>{state[key].splice(i,1);editor(key,fields)};box.append(del);root.append(box)})}
const fields={socials:[{key:"icon",label:"Icon"},{key:"title",label:"Title"},{key:"url",label:"URL"},{key:"enabled",label:"Enabled",type:"checkbox"}],scripts:[{key:"name",label:"Name"},{key:"description",label:"Description",type:"textarea"},{key:"url",label:"Script URL"},{key:"tags",label:"Tags (comma separated)"},{key:"thumbnail",label:"Thumbnail"},{key:"enabled",label:"Enabled",type:"checkbox"}],stats:[{key:"label",label:"Label"},{key:"value",label:"Value"},{key:"icon",label:"Icon"}]};
function renderEditors(){Object.entries(fields).forEach(([key,fs])=>editor(key,fs));const root=$("#sectionEditor");root.innerHTML="";Object.entries(state.sections||{}).forEach(([key,item])=>{const box=document.createElement("div");box.className="item";box.innerHTML=`<label>${key} title<input value="${item.title||""}"></label><label><input type="checkbox" ${item.enabled!==false?"checked":""}> Enabled</label>`;const [title,enabled]=box.querySelectorAll("input");title.oninput=()=>item.title=title.value;enabled.onchange=()=>item.enabled=enabled.checked;root.append(box)})}
async function load(){try{Object.assign(state,await request("/api/site-config"));bindPaths();renderEditors();status("Configuration loaded") }catch(e){status(e.message,true)}}
document.addEventListener("click",e=>{const add=e.target.closest("[data-add]");if(add){const key=add.dataset.add;state[key]=state[key]||[];state[key].push(key==="stats"?{label:"New stat",value:"0",icon:"★"}:key==="socials"?{icon:"◉",title:"New link",url:"#",enabled:true}:{name:"New script",description:"",url:"",tags:[],thumbnail:"",enabled:true});renderEditors()}});$("#save").onclick=async()=>{try{await request("/api/site-config",{method:"PUT",body:JSON.stringify(state)});status("Saved successfully")}catch(e){status(e.message,true)}};$("#reset").onclick=load;load();
